contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.index, name='index'),
]

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'
urlpatterns = [
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

nowosad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('plants/', include('plants.urls')),
    path('gallery/', include('gallery.urls')),
    path('', RedirectView.as_view(url='/main/')),
    path('contact/', include('contact.urls')),
]

plants/urls.py
from django.urls import path
from . import views

app_name = 'plants'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:plant_id>/', views.detail, name='detail'),
]

contact/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    alt_title = models.CharField(max_length=100)
    img_src = models.ImageField(null=True)

    def __str__(self):
        return self.alt_title

main/models.py
from django.db import models

# Create your models here.

plants/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class Plant(models.Model):
    plant_name = models.CharField(max_length=100)
    img_src = models.ImageField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.plant_name

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    contact_title = forms.CharField(required=True)
    contact_msg = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Imię:"
        self.fields['contact_email'].label = "Adres e-mail:"
        self.fields['contact_title'].label = "Temat:"
        self.fields['contact_msg'].label = "Treść wiadomości:"

contact/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.template.loader import get_template
from .forms import ContactForm

# Create your views here.
def index(request):
    form_class = ContactForm
    message = ""

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            contact_title = request.POST.get('contact_title', '')
            form_content = request.POST.get('contact_msg', '')

            email = EmailMessage(subject=contact_title, body=form_content, from_email=contact_email,
                                 to=('nowosad.smolec@gmail.com',))
            email.send()
            message = "Wiadomość wysłano."
            context = {'contact_form': ContactForm,
                       'message': message}
            return render(request, 'contact/index.html', context)
        else:
            message = "Nie udało się wysłać wiadomości."
            context = {'contact_form': form_class,
                       'message': message}
            return render(request, 'contact/index.html', context)
    else:
        context = {'contact_form': form_class,
                   'message': message}
        return render(request, 'contact/index.html', context)

gallery/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Image

# Create your views here.
def index(request):
    images_list = Image.objects.order_by('alt_title')
    context = {'images_list': images_list}
    return render(request, 'gallery/index.html', context)

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

plants/views.py
from django.shortcuts import render, get_object_or_404
from .models import Plant, Category


# Create your views here.
def index(request):
    plants = Plant.objects
    plants_ch = plants.filter(category=2).order_by('plant_name')
    plants_by = plants.filter(category=1).order_by('plant_name')
    plants_ba = plants.filter(category=3).order_by('plant_name')
    plants_ra = plants.filter(category=4).order_by('plant_name')
    context = {'chryzantemy': plants_ch,
               'balkonowe': plants_ba,
               'rabatowe': plants_ra,
               'byliny': plants_by}
    return render(request, 'plants/index.html', context)


def detail(request, plant_id):
    plant = get_object_or_404(Plant, pk=plant_id)
    return render(request, 'plants/detail.html', {'plant': plant})

contact/templates/contact/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Kontakt | {% endblock %}

{% block content %}
<div class="row content">
    <div style="width:100%">
        <h1 style="text-align: center; margin-bottom:10px;">Kontakt</h1>
    </div>
    <div class="col-md-6">
        <div class="contact-form">
            {% if not message == '' %}
                <h3>{{ message }}</h3>
                <hr />
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                {{ contact_form }}
                <input type="submit" />
            </form>
        </div>
    </div>
    <div class="col-md-6" style="">
        <br />
        <br />
            <h3 align="center">Gospodarstwo Ogrodnicze <br />Barbara i Andrzej Nowosad</h3>
            <p align="center">
                    ul. Starowiejska 44, Smolec<br />
                    55-080 Kąty Wrocławskie<br />
                    <br />
                    <strong>tel.:</strong><br />
                    +48 602 441 214<br />
                    +48 695 663 337<br />
                    <br />
                    <strong>tel / fax:</strong><br />
                    +48 71 316 85 99
            </p>
            <p align="center">
                <br />
                <strong>e-mail:</strong><br /><a href="mailto:andrzej-nowosad@o2.pl">andrzej-nowosad@o2.pl</a><br />
            </p>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Galeria | {% endblock %}

{% block content %}
    {% if images_list %}
        <div class="row content">
            <div style="width:100%">
                <h1 style="text-align: center; margin-bottom:10px;">Galeria</h1>
            </div>
            <div class="row-flexing">
                    <div class="column">
                        {% for img in images_list|slice:":4" %}
                            <img class="gallery-img" src="{{ img.img_src.url }}" />
                        {% endfor %}
                    </div>
                    <div class="column">
                        {% for img in images_list|slice:"4:8" %}
                            <img class="gallery-img" src="{{ img.img_src.url }}" />
                        {% endfor %}
                    </div>
                    <div class="column">
                        {% for img in images_list|slice:"8:12" %}
                            <img class="gallery-img" src="{{ img.img_src.url }}" />
                        {% endfor %}
                    </div>
                    <div class="column">
                        {% for img in images_list|slice:"12:" %}
                            <img class="gallery-img" src="{{ img.img_src.url }}" />
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <img class="modal-content" id="modal-img">
        </div>
    {% else %}
        <div class="row content">
            <div style="width:100%">
                <h1 style="text-align: center; margin-bottom:10px;">Galeria</h1>
            </div>
            <div style="width:100%">
                <p align="center">Aktualnie nie ma zdjęć w galerii.</p>
            </div>
        </div>
    {% endif %}

<script>
    var modal = document.getElementById('myModal');

    var modalImg = document.getElementById("modal-img");

    var span = document.getElementsByClassName("close")[0];

    var elements = document.getElementsByClassName("gallery-img");
    for (var i = 0, len = elements.length; i < len; i++) {
        elements[i].onclick = function(){
            modal.style.display = "block";
            modalImg.src = this.src;
        }
    }

    span.onclick = function() {
        modal.style.display = "none";
    }
</script>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{% endblock %}

{% block content %}
<div class="row content">
    <h2 style="margin-top: 40px; margin-bottom: 20px;">O firmie</h2>
    <p align="justify" style="width: 60%; margin-bottom: 12px;">Gospodarstwo Ogrodnicze Nowosad to rodzinna firma istniejąca na rynku od 1980 roku.</p>
    <p align="justify" style="margin-bottom: 12px; width: 60%;">Obecnie gospodarstwo zajmuje się produkcją kwiatów doniczkowych.
    W ofercie handlowej znajdują się <strong>kwiaty rabatowe, balkonowe, byliny i trawy</strong> oraz szeroki wybór
    <strong>chryzantem doniczkowych.</strong> </p>
    <p align="justify" style="width: 60%; margin-bottom: 12px;">Uprawa prowadzona jest na powierzchni ponad 12 000m<sup>2</sup> pod osłonami oraz na 2ha kontenerowni.</p>
    <p align="justify" style="width: 60%;">Gospodarstwo mieści się w podwrocławskim Smolcu. Zapraszamy do zapoznania się naszą ofertą.</p>
    <br />
    <br />
    <p align="right"><a href="{% url 'plants:index' %}" class="btn btn-primary btn-lg">Sprawdź naszą ofertę &raquo;</a></p>
</div>
{% endblock %}

plants/templates/plants/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ plant.plant_name }} | {% endblock %}

{% block content %}
<div class="row content">
    <div class="col-md-3 item-container">
        <img class="item-img" src="{{ plant.img_src.url }}" />
        <div class="caption">
            <p>{{ plant.plant_name }}</p>
            <p>{{plant.category.category_name}}</p>
        </div>
    </div>
    <div style="width:100%; text-align: center;">
        <p>{{ plant.description }}</p>
    </div>
</div>
{% endblock %}

plants/templates/plants/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Oferowane rośliny | {% endblock %}

{% block content %}
    {% if balkonowe %}
<div class="row content">
    <div style="width:100%">
        <h1 style="text-align: center; margin-bottom:10px;">Rośliny w ofercie:</h1>
    </div>
    <div class="row-flexing">
        <div class="column">
            <h3>Kwiaty balkonowe:</h3>
            <ul>
                {% for bal in balkonowe %}
                    <li>{{ bal.plant_name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="column">
            <h3>Kwiaty rabatowe:</h3>
            <ul>
                {% for rab in rabatowe %}
                    <li>{{ rab.plant_name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="column">
            <h3>Chryzantemy doniczkowe:</h3>
            <ul>
                {% for chr in chryzantemy %}
                    <li>{{ chr.plant_name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="column">
            <h3>Byliny i trawy:</h3>
            <ul>
                {% for byl in byliny %}
                    <li>{{ byl.plant_name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
    {% else %}
<div class="row content">
    <div style="width:100%">
        <h1 style="text-align: center; margin-bottom:10px;">Rośliny w ofercie:</h1>
    </div>
    <div style="width:100%">
        <h3>Aktualnie nie posiadamy roślin w ofercie.</h3>
    </div>
</div>
    {% endif %}
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <title>{% block title %}{% endblock %} Gospodarstwo Ogrodnicze Nowosad</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="icon" href="{% static 'images/background.jpg' %}" type="image/x-icon"/>
    <link rel="shortcut icon" href="{% static 'images/background.jpg' %}" type="image/x-icon"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Open+Sans" rel="stylesheet">
</head>
<body>
    <header>
        <div class="header-bar">
            <div style="display: inline-block;">
                <a href="{% url 'main:index' %}">
                    <img class="logo" src="{% static 'images/Nowosad-logo-small.png' %}" />
                </a>
            </div>
            <div style="display: inline-block; float: right; padding-right: 10px; padding-top: 5px; text-align: right; color: white;">
                <h4>Gospodarstwo Ogrodnicze <br />Barbara i Andrzej Nowosad</h4>
                <h5>ul. Starowiejska 44, Smolec<br />55-080 Kąty Wrocławskie</h5>
            </div>

        </div>
        <nav>
            <ul class="menu">
                <li><a href="{% url 'main:index' %}">Strona Główna</a></li>
                <li><a href="{% url 'plants:index' %}">Oferta</a></li>
                <li><a href="{% url 'gallery:index' %}">Galeria</a></li>
                <li><a href="{% url 'contact:index' %}">Kontakt</a></li>
            </ul>
        </nav>
    </header>
    <img class="bg-image" src="{% static 'images/background.jpg' %}" />
    {% block content %}{% endblock %}
    <footer>
        <div class="row">
            <div id="map" class="col-md-4 map-element container"></div>
        </div>
        <div class="row footer-content">
            <br />
            <strong>
                <p align="center">&copy; Gospodarstwo Ogrodnicze Andrzej Nowosad</p>
            </strong>
            <br />
            <br />
        </div>
    </footer>
    <script>
        function initMap() {
            google.maps.visualRefresh = true;
            var smolec = { lat: 51.0758446, lng: 16.870288 };
            var mapDiv = document.getElementById('map');
            var map = new google.maps.Map(mapDiv, {
                center: smolec,
                zoom: 11
            });
            var outerCoords = [
                { lat: 51.074372, lng: 16.868557 },
                { lat: 51.074329, lng: 16.869171 },
                { lat: 51.075890, lng: 16.869725 },
                { lat: 51.075864, lng: 16.870228 },
                { lat: 51.075730, lng: 16.870382 },
                { lat: 51.074281, lng: 16.869897 },
                { lat: 51.073358, lng: 16.871550 },
                { lat: 51.072930, lng: 16.871440 },
                { lat: 51.073128, lng: 16.870732 },
                { lat: 51.071299, lng: 16.870087 },
                { lat: 51.071381, lng: 16.869394 },
                { lat: 51.073304, lng: 16.870072 },
                { lat: 51.073742, lng: 16.868320 }
            ];
            var polygon = new google.maps.Polygon({
                paths: outerCoords,
                strokeColor: '#FFC107',
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: '#FFC107',
                fillOpacity: 0.35
            });
            polygon.setMap(map);
            var marker = new google.maps.Marker({
                map: map,
                position: smolec,
                title: 'Gospodarstwo Ogrodnicze - Andrzej Nowosad'
            });
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_5MetfhKkVwWxbqmCKHcKgm30zpwCRBI&callback=initMap"></script>
</body>
</html>